name: Build and deploy ASP.Net Core app to Azure Web App - FSKaficProjekat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: dotnet publish
        run: dotnet publish -c Release -o myapp
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: FSKaficProjekat
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_744185B82A2B42F3B920A05745BBC0AC }}
          package: 'myapp'
